---
functional:
- У пользователя есть вомможность зарегистрироваться и авторзоваться на сайте
- У вользователя есть возможность авторизоваться с помощью "GitHub" и "Discord"
- У пользователя есть возможность самому решить с кем ему играть (с ботом, другом или с рандомным человеком)
- У пользователя есть возможность самому менять настройки игры на сайте 
- У пользователя есть возможность менять язык задачи во время игры 
- У пользователя есть возможность создавать турниры с определенными настройками 
- У пользователя есть возможность общения во время игры(только с зарегистрированнымми пользователями )
- У пользователя есть возможность просматривать завершенную игру
- Пользователь получает очки, на основе которых формируется рейтинг за неделю, месяц и за все время 
non-functional:
- Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен быть удобным на мобильном устройстве
- Сайт должен быть протестирован на совместимость с последними версиями браузеров
- Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit: 
- У пользователя должна быть возможность настраивать свой профиль(аватар)
- У пользователя должна быть возможность изменять настройки профиля
- У пользователя должна быть возможность просматривать рейтинг пользователей 